name: VPS Deploy

on:
  workflow_dispatch:
    inputs:
      vps_name:
        description: "Name of the VPS"
        required: true
      vps_pass:
        description: "Password for VPS"
        required: true
      discord_id:
        description: "Discord ID of the user"
        required: true

  schedule:
    - cron: "0 */6 * * *"  # Restart every 6 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=${{ github.event.inputs.vps_name }} --ssh

    - name: Create VPS User
      run: |
        sudo adduser --disabled-password --gecos "" ${{ github.event.inputs.vps_name }}
        echo "${{ github.event.inputs.vps_name }}:${{ github.event.inputs.vps_pass }}" | sudo chpasswd
        sudo usermod -aG sudo ${{ github.event.inputs.vps_name }}

    - name: Save VPS Info
      run: |
        echo "VPS Name: ${{ github.event.inputs.vps_name }}" > vps_info.txt
        echo "Password: ${{ github.event.inputs.vps_pass }}" >> vps_info.txt
        echo "IP: $(tailscale ip -4)" >> vps_info.txt
        echo "SSH: ssh ${{ github.event.inputs.vps_name }}@$(tailscale ip -4)" >> vps_info.txt
        echo "DiscordID: ${{ github.event.inputs.discord_id }}" >> vps_info.txt
        cat vps_info.txt

    - name: Upload VPS Info
      uses: actions/upload-artifact@v4
      with:
        name: vps-details
        path: vps_info.txt

    - name: Keep VPS Running
      run: |
        sleep 6h
