name: LithManager-like Windows VM minimal (No VPN)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable Remote Desktop & Create User
      shell: pwsh
      run: |
        Write-Output "Enabling RDP and creating user..."
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        net user lithuser Password123 /add
        net localgroup administrators lithuser /add

    - name: Install Google Chrome
      shell: pwsh
      run: |
        Write-Output "Installing Google Chrome..."
        choco install -y googlechrome

    - name: Show public IP
      shell: pwsh
      run: |
        $publicIp = (Invoke-RestMethod -Uri 'http://ifconfig.me/ip').Trim()
        Write-Output "Public IP: $publicIp"

    - name: Keep session alive for 6 hours
      shell: pwsh
      run: Start-Sleep -Seconds 21600
